In [1]:
import pandas as pd

In [2]:
df_fang = pd.read_csv("adjusted_datasets/fang_dataset_adjusted.csv")

In [3]:
df_fang

,Unnamed: 0,SMILES,LOG HLM_CLint (mL/min/kg),hlm_value_unscaled,hlm_value_unscaled_log1p,hlm_value_scaled,hlm_value_scaled_log1p,dataset,data_year
0,0,CNc1cc(Nc2cccn(-c3ccccn3)c2=O)nn2c(C(=O)N[C@@H...,0.675687,4.739,1.747285,4.739,1.747285,fang_dataset,2023
1,1,CCOc1cc2nn(CCC(C)(C)O)cc2cc1NC(=O)c1cccc(C(F)F)n1,0.675687,4.739,1.747285,4.739,1.747285,fang_dataset,2023
2,2,CN(c1ncc(F)cn1)[C@H]1CCCNC1,0.675687,4.739,1.747285,4.739,1.747285,fang_dataset,2023
3,3,CC(C)(Oc1ccc(-c2cnc(N)c(-c3ccc(Cl)cc3)c2)cc1)C...,0.675687,4.739,1.747285,4.739,1.747285,fang_dataset,2023
4,4,CC(C)(O)CCn1cc2cc(NC(=O)c3cccc(C(F)(F)F)n3)c(C...,0.996380,9.917,2.390321,9.917,2.390321,fang_dataset,2023
...,...,...,...,...,...,...,...,...,...
3082,3082,c1sc(NCC2CCCO2)nc1C12CC3CC(CC(C3)C1)C2,1.659650,45.672,3.843144,45.672,3.843144,fang_dataset,2023
3083,3083,CCN1CCOC(C(=O)N2CCC(c3cn[nH]c3)CC2)C1,0.675687,4.739,1.747285,4.739,1.747285,fang_dataset,2023
3084,3084,NC(=O)c1noc([C@@H](CCCC2CCCCC2)CC(=O)NO)n1,0.863799,7.308,2.117219,7.308,2.117219,fang_dataset,2023
3085,3085,CCCCCCCCc1ccc(CC[C@](N)(CO)COP(=O)(O)O)cc1,0.881385,7.610,2.152924,7.610,2.152924,fang_dataset,2023
3086,3086,Cc1cccc(/C=N/Nc2cc(N3CCOCC3)n3nc(-c4ccncc4)cc3...,1.507059,32.141,3.500771,32.141,3.500771,fang_dataset,2023

In [4]:
df_fang["mol_id"] = [f"fang_{i}" for i in range(1, len(df_fang) + 1)]
df_fang["scaling_was_applied"] = "False" 
df_fang

,Unnamed: 0,SMILES,LOG HLM_CLint (mL/min/kg),hlm_value_unscaled,hlm_value_unscaled_log1p,hlm_value_scaled,hlm_value_scaled_log1p,dataset,data_year,mol_id,scaling_was_applied
0,0,CNc1cc(Nc2cccn(-c3ccccn3)c2=O)nn2c(C(=O)N[C@@H...,0.675687,4.739,1.747285,4.739,1.747285,fang_dataset,2023,fang_1,False
1,1,CCOc1cc2nn(CCC(C)(C)O)cc2cc1NC(=O)c1cccc(C(F)F)n1,0.675687,4.739,1.747285,4.739,1.747285,fang_dataset,2023,fang_2,False
2,2,CN(c1ncc(F)cn1)[C@H]1CCCNC1,0.675687,4.739,1.747285,4.739,1.747285,fang_dataset,2023,fang_3,False
3,3,CC(C)(Oc1ccc(-c2cnc(N)c(-c3ccc(Cl)cc3)c2)cc1)C...,0.675687,4.739,1.747285,4.739,1.747285,fang_dataset,2023,fang_4,False
4,4,CC(C)(O)CCn1cc2cc(NC(=O)c3cccc(C(F)(F)F)n3)c(C...,0.996380,9.917,2.390321,9.917,2.390321,fang_dataset,2023,fang_5,False
...,...,...,...,...,...,...,...,...,...,...,...
3082,3082,c1sc(NCC2CCCO2)nc1C12CC3CC(CC(C3)C1)C2,1.659650,45.672,3.843144,45.672,3.843144,fang_dataset,2023,fang_3083,False
3083,3083,CCN1CCOC(C(=O)N2CCC(c3cn[nH]c3)CC2)C1,0.675687,4.739,1.747285,4.739,1.747285,fang_dataset,2023,fang_3084,False
3084,3084,NC(=O)c1noc([C@@H](CCCC2CCCCC2)CC(=O)NO)n1,0.863799,7.308,2.117219,7.308,2.117219,fang_dataset,2023,fang_3085,False
3085,3085,CCCCCCCCc1ccc(CC[C@](N)(CO)COP(=O)(O)O)cc1,0.881385,7.610,2.152924,7.610,2.152924,fang_dataset,2023,fang_3086,False
3086,3086,Cc1cccc(/C=N/Nc2cc(N3CCOCC3)n3nc(-c4ccncc4)cc3...,1.507059,32.141,3.500771,32.141,3.500771,fang_dataset,2023,fang_3087,False

In [5]:
df_openadmet_expansion = pd.read_csv("adjusted_datasets/openadmet_expansion_train_adjusted.csv")

In [6]:
df_openadmet_expansion

,Unnamed: 0,Molecule Name,SMILES,HLM CLint,hlm_value_unscaled,hlm_value_unscaled_log1p,hlm_value_scaled,hlm_value_scaled_log1p,dataset,data_year
0,0,E-0001321,CN1CCC[C@H]1COc1ccc(-c2nc3cc(-c4ccc5[nH]c(-c6c...,56.4,56.4,4.050044,56.4,4.050044,openadmet_expansion_train,2026
1,1,E-0001780,COc1ccc2c(c1)c1cc3cnccc3c(C)c1n2C,160.4,160.4,5.083886,160.4,5.083886,openadmet_expansion_train,2026
2,2,E-0002019,CN(C)CCCOc1ccc(-c2nc3cc(NC(=O)c4ccc5[nH]c(-c6c...,9.5,9.5,2.351375,9.5,2.351375,openadmet_expansion_train,2026
3,3,E-0002269,CN(C)CC(O)COc1ccc2nc(-c3ccc(-c4nc5ccc(OCC(O)CN...,18.9,18.9,2.990720,18.9,2.990720,openadmet_expansion_train,2026
4,4,E-0002284,COc1ccc(-c2nc3ccc(OCCCN(C)C)cc3[nH]2)cc1NC(=O)...,14.9,14.9,2.766319,14.9,2.766319,openadmet_expansion_train,2026
...,...,...,...,...,...,...,...,...,...,...
3754,3754,E-0019488,Fc1c(OCCN2CCOCC2)ccc(-c2csc3cncn23)c1F,31.3,31.3,3.475067,31.3,3.475067,openadmet_expansion_train,2026
3755,3755,E-0020024,CNc1cc(N2C[C@@H]3[C@H](C2)[C@H]3NC(=O)c2cc3cc(...,11.5,11.5,2.525729,11.5,2.525729,openadmet_expansion_train,2026
3756,3756,E-0020048,Cc1c(OCCN2CC3(CN(C)C3)C2)ccc(-c2cc(C)c3ccncc3c...,8.1,8.1,2.208274,8.1,2.208274,openadmet_expansion_train,2026
3757,3757,E-0020066,Fc1cc(-c2cc3cnccc3nc2Cl)c(F)cc1OCCN1CCOCC1,39.3,39.3,3.696351,39.3,3.696351,openadmet_expansion_train,2026
3758,3758,E-0020067,Fc1cc(-c2cc3cnccc3c(Cl)c2F)c(F)cc1OCCN1CCOCC1,84.9,84.9,4.453184,84.9,4.453184,openadmet_expansion_train,2026

In [7]:
df_openadmet_expansion = df_openadmet_expansion.rename(columns={"Molecule Name": "mol_id"})
df_openadmet_expansion["scaling_was_applied"] = "False" 
df_openadmet_expansion

,Unnamed: 0,mol_id,SMILES,HLM CLint,hlm_value_unscaled,hlm_value_unscaled_log1p,hlm_value_scaled,hlm_value_scaled_log1p,dataset,data_year,scaling_was_applied
0,0,E-0001321,CN1CCC[C@H]1COc1ccc(-c2nc3cc(-c4ccc5[nH]c(-c6c...,56.4,56.4,4.050044,56.4,4.050044,openadmet_expansion_train,2026,False
1,1,E-0001780,COc1ccc2c(c1)c1cc3cnccc3c(C)c1n2C,160.4,160.4,5.083886,160.4,5.083886,openadmet_expansion_train,2026,False
2,2,E-0002019,CN(C)CCCOc1ccc(-c2nc3cc(NC(=O)c4ccc5[nH]c(-c6c...,9.5,9.5,2.351375,9.5,2.351375,openadmet_expansion_train,2026,False
3,3,E-0002269,CN(C)CC(O)COc1ccc2nc(-c3ccc(-c4nc5ccc(OCC(O)CN...,18.9,18.9,2.990720,18.9,2.990720,openadmet_expansion_train,2026,False
4,4,E-0002284,COc1ccc(-c2nc3ccc(OCCCN(C)C)cc3[nH]2)cc1NC(=O)...,14.9,14.9,2.766319,14.9,2.766319,openadmet_expansion_train,2026,False
...,...,...,...,...,...,...,...,...,...,...,...
3754,3754,E-0019488,Fc1c(OCCN2CCOCC2)ccc(-c2csc3cncn23)c1F,31.3,31.3,3.475067,31.3,3.475067,openadmet_expansion_train,2026,False
3755,3755,E-0020024,CNc1cc(N2C[C@@H]3[C@H](C2)[C@H]3NC(=O)c2cc3cc(...,11.5,11.5,2.525729,11.5,2.525729,openadmet_expansion_train,2026,False
3756,3756,E-0020048,Cc1c(OCCN2CC3(CN(C)C3)C2)ccc(-c2cc(C)c3ccncc3c...,8.1,8.1,2.208274,8.1,2.208274,openadmet_expansion_train,2026,False
3757,3757,E-0020066,Fc1cc(-c2cc3cnccc3nc2Cl)c(F)cc1OCCN1CCOCC1,39.3,39.3,3.696351,39.3,3.696351,openadmet_expansion_train,2026,False
3758,3758,E-0020067,Fc1cc(-c2cc3cnccc3c(Cl)c2F)c(F)cc1OCCN1CCOCC1,84.9,84.9,4.453184,84.9,4.453184,openadmet_expansion_train,2026,False

In [8]:
df_openadmet_polaris = pd.read_csv("adjusted_datasets/antiviral_admet_2025_unblinded_adjusted.csv")

In [9]:
df_openadmet_polaris

,Unnamed: 0,CXSMILES,HLM,Molecule Name,Set,hlm_value_unscaled,hlm_value_unscaled_log1p,hlm_value_scaled,hlm_value_scaled_log1p,dataset,data_year
0,0,CN(C1=CC=C2CNCC2=C1)[C@H](C(=O)NCC(F)F)C1=CC(C...,17.1,ASAP-0031351,Train,17.1,2.895912,17.5788,2.922021,openadmet_polaris,2025
1,1,N#CC1=CC2=C(C=C1NC(=O)C1=CC(F)=CC3=C1C=NN3)CNC2,16.7,ASAP-0031265,Train,16.7,2.873565,17.1676,2.899640,openadmet_polaris,2025
2,2,O=C(NC1=CC=C2CNCC2=C1)C1=CC(F)=CC(C2=CNN=C2)=C1,36.3,ASAP-0031004,Train,36.3,3.618993,37.3164,3.645878,openadmet_polaris,2025
3,3,COCCNC(=O)[C@H](NC1=CC=C2CNCC2=C1)C1=CC(Cl)=CC...,19.7,ASAP-0030761,Train,19.7,3.030134,20.2516,3.056432,openadmet_polaris,2025
4,4,O=C(NC1=CC(Br)=C2CNCC2=C1)C1=CC(F)=CC2=C1C=NN2,13.6,ASAP-0030792,Train,13.6,2.681022,13.9808,2.706769,openadmet_polaris,2025
...,...,...,...,...,...,...,...,...,...,...,...
398,398,C[C@H]1CN(C2=CN=CC3=CC=CC=C23)C(=O)[C@@]12CN(C...,85.0,ASAP-0014770,Test,85.0,4.454347,87.3800,4.481646,openadmet_polaris,2025
399,399,C[C@H]1CN(C2=CN=CC3=CC=CC=C23)C(=O)[C@@]12CN(C...,48.0,ASAP-0014773,Test,48.0,3.891820,49.3440,3.918879,openadmet_polaris,2025
400,400,COC[C@H]1CN(C2=CN=CC3=CC=CC=C23)C(=O)[C@@]12CN...,156.0,ASAP-0014789,Test,156.0,5.056246,160.3680,5.083687,openadmet_polaris,2025
401,401,C[C@H]1CN(C2=CN=CC3=CC=CC=C23)C(=O)[C@@]12CN(C...,406.0,ASAP-0014632,Test,406.0,6.008813,417.3680,6.036361,openadmet_polaris,2025
402,402,CC1=NC=C(CN2C[C@@]3(C(=O)N(C4=CN=CC5=CC=CC=C45...,143.0,ASAP-0014619,Test,143.0,4.969813,147.0040,4.997239,openadmet_polaris,2025

In [10]:
df_openadmet_polaris = df_openadmet_polaris.rename(columns={"CXSMILES": "SMILES"})
df_openadmet_polaris = df_openadmet_polaris.rename(columns={"Molecule Name": "mol_id"})
df_openadmet_polaris["scaling_was_applied"] = "True" 
df_openadmet_polaris

,Unnamed: 0,SMILES,HLM,mol_id,Set,hlm_value_unscaled,hlm_value_unscaled_log1p,hlm_value_scaled,hlm_value_scaled_log1p,dataset,data_year,scaling_was_applied
0,0,CN(C1=CC=C2CNCC2=C1)[C@H](C(=O)NCC(F)F)C1=CC(C...,17.1,ASAP-0031351,Train,17.1,2.895912,17.5788,2.922021,openadmet_polaris,2025,True
1,1,N#CC1=CC2=C(C=C1NC(=O)C1=CC(F)=CC3=C1C=NN3)CNC2,16.7,ASAP-0031265,Train,16.7,2.873565,17.1676,2.899640,openadmet_polaris,2025,True
2,2,O=C(NC1=CC=C2CNCC2=C1)C1=CC(F)=CC(C2=CNN=C2)=C1,36.3,ASAP-0031004,Train,36.3,3.618993,37.3164,3.645878,openadmet_polaris,2025,True
3,3,COCCNC(=O)[C@H](NC1=CC=C2CNCC2=C1)C1=CC(Cl)=CC...,19.7,ASAP-0030761,Train,19.7,3.030134,20.2516,3.056432,openadmet_polaris,2025,True
4,4,O=C(NC1=CC(Br)=C2CNCC2=C1)C1=CC(F)=CC2=C1C=NN2,13.6,ASAP-0030792,Train,13.6,2.681022,13.9808,2.706769,openadmet_polaris,2025,True
...,...,...,...,...,...,...,...,...,...,...,...,...
398,398,C[C@H]1CN(C2=CN=CC3=CC=CC=C23)C(=O)[C@@]12CN(C...,85.0,ASAP-0014770,Test,85.0,4.454347,87.3800,4.481646,openadmet_polaris,2025,True
399,399,C[C@H]1CN(C2=CN=CC3=CC=CC=C23)C(=O)[C@@]12CN(C...,48.0,ASAP-0014773,Test,48.0,3.891820,49.3440,3.918879,openadmet_polaris,2025,True
400,400,COC[C@H]1CN(C2=CN=CC3=CC=CC=C23)C(=O)[C@@]12CN...,156.0,ASAP-0014789,Test,156.0,5.056246,160.3680,5.083687,openadmet_polaris,2025,True
401,401,C[C@H]1CN(C2=CN=CC3=CC=CC=C23)C(=O)[C@@]12CN(C...,406.0,ASAP-0014632,Test,406.0,6.008813,417.3680,6.036361,openadmet_polaris,2025,True
402,402,CC1=NC=C(CN2C[C@@]3(C(=O)N(C4=CN=CC5=CC=CC=C45...,143.0,ASAP-0014619,Test,143.0,4.969813,147.0040,4.997239,openadmet_polaris,2025,True

In [11]:
df_chembl = pd.read_csv("adjusted_datasets/chembl_hlm_adjusted.csv")

In [12]:
df_chembl

,Unnamed: 0,activity_id,molecule_chembl_id,smiles,structure_status,target_chembl_id,target_name,assay_chembl_id,document_chembl_id,data_year,...,activity_comment,assay_type,assay_description,classification_text,classification_bucket,hlm_value_unscaled,hlm_value_unscaled_log1p,hlm_value_scaled,hlm_value_scaled_log1p,dataset
0,0,33031,CHEMBL306457,NC(=O)C(C[C@H](O)[C@H](Cc1ccccc1)NC(=O)c1cnc2c...,smiles_found,CHEMBL372,Homo sapiens,CHEMBL695026,CHEMBL1147552,2004.0,...,NaN,F,In vitro oxidative metabolic stability measure...,in vitro oxidative metabolic stability measure...,chembl_hlm_intrinsic,47.7,3.885679,47.700,3.885679,chembl_dataset
1,1,34270,CHEMBL66457,CC(C)(O)CC[C@H](C[C@H](O)[C@H](Cc1ccccc1)NC(=O...,smiles_found,CHEMBL372,Homo sapiens,CHEMBL695026,CHEMBL1147552,2004.0,...,NaN,F,In vitro oxidative metabolic stability measure...,in vitro oxidative metabolic stability measure...,chembl_hlm_intrinsic,4.9,1.774952,4.900,1.774952,chembl_dataset
2,2,34274,CHEMBL304053,CC(C)(O)CCC(C[C@H](O)[C@H](Cc1ccccc1F)NC(=O)c1...,smiles_found,CHEMBL372,Homo sapiens,CHEMBL695026,CHEMBL1147552,2004.0,...,NaN,F,In vitro oxidative metabolic stability measure...,in vitro oxidative metabolic stability measure...,chembl_hlm_intrinsic,16.5,2.862201,16.500,2.862201,chembl_dataset
3,3,35507,CHEMBL68366,CC(C)(F)CC[C@H](C[C@H](O)[C@H](Cc1ccccc1)NC(=O...,smiles_found,CHEMBL372,Homo sapiens,CHEMBL695026,CHEMBL1147552,2004.0,...,NaN,F,In vitro oxidative metabolic stability measure...,in vitro oxidative metabolic stability measure...,chembl_hlm_intrinsic,8.0,2.197225,8.000,2.197225,chembl_dataset
4,4,39099,CHEMBL303673,O=C(N[C@@H](Cc1ccccc1)[C@@H](O)CC(C(=O)NO)C1CC...,smiles_found,CHEMBL372,Homo sapiens,CHEMBL695026,CHEMBL1147552,2004.0,...,NaN,F,In vitro oxidative metabolic stability measure...,in vitro oxidative metabolic stability measure...,chembl_hlm_intrinsic,6.1,1.960095,6.100,1.960095,chembl_dataset
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11697,11697,26316940,CHEMBL5712066,C=CC(=O)Nc1ccc(C(=O)NC2CCN(Cc3ccc(-c4nc5cc[nH]...,smiles_found,CHEMBL612558,ADMET,CHEMBL5712039,CHEMBL5705908,2019.0,...,NaN,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic,12.0,2.564949,12.336,2.590467,chembl_dataset
11698,11698,26316941,CHEMBL2325741,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2nc[nH]...,smiles_found,CHEMBL612558,ADMET,CHEMBL5712039,CHEMBL5705908,2019.0,...,NaN,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic,14.0,2.708050,14.392,2.733848,chembl_dataset
11699,11699,26316942,CHEMBL2177390,CC(C)NC[C@@H](C(=O)N1CCN(c2ncnc3c2[C@H](C)C[C@...,smiles_found,CHEMBL612558,ADMET,CHEMBL5712039,CHEMBL5705908,2019.0,...,NaN,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic,12.0,2.564949,12.336,2.590467,chembl_dataset
11700,11700,26316943,CHEMBL1079175,NC1(c2ccc(-c3nc4ccn5c(=O)[nH]nc5c4cc3-c3ccccc3...,smiles_found,CHEMBL612558,ADMET,CHEMBL5712039,CHEMBL5705908,2019.0,...,NaN,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic,1.0,0.693147,1.028,0.707050,chembl_dataset
11701,11701,26316944,CHEMBL4795065,C=CC(=O)Nc1ccc2[nH]c(=O)n(C3CCN(Cc4ccc(-c5nc6c...,smiles_found,CHEMBL612558,ADMET,CHEMBL5712039,CHEMBL5705908,2019.0,...,NaN,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic,5.0,1.791759,5.140,1.814825,chembl_dataset

In [13]:
df_chembl = df_chembl.rename(columns={"smiles": "SMILES"})
df_chembl = df_chembl.rename(columns={"molecule_chembl_id": "mol_id"})
df_chembl["scaling_was_applied"] = df_chembl["standard_units"].map({
    "mL.min-1.kg-1": False,
    "mL.min-1.g-1": True
})
df_chembl

,Unnamed: 0,activity_id,mol_id,SMILES,structure_status,target_chembl_id,target_name,assay_chembl_id,document_chembl_id,data_year,...,assay_type,assay_description,classification_text,classification_bucket,hlm_value_unscaled,hlm_value_unscaled_log1p,hlm_value_scaled,hlm_value_scaled_log1p,dataset,scaling_was_applied
0,0,33031,CHEMBL306457,NC(=O)C(C[C@H](O)[C@H](Cc1ccccc1)NC(=O)c1cnc2c...,smiles_found,CHEMBL372,Homo sapiens,CHEMBL695026,CHEMBL1147552,2004.0,...,F,In vitro oxidative metabolic stability measure...,in vitro oxidative metabolic stability measure...,chembl_hlm_intrinsic,47.7,3.885679,47.700,3.885679,chembl_dataset,False
1,1,34270,CHEMBL66457,CC(C)(O)CC[C@H](C[C@H](O)[C@H](Cc1ccccc1)NC(=O...,smiles_found,CHEMBL372,Homo sapiens,CHEMBL695026,CHEMBL1147552,2004.0,...,F,In vitro oxidative metabolic stability measure...,in vitro oxidative metabolic stability measure...,chembl_hlm_intrinsic,4.9,1.774952,4.900,1.774952,chembl_dataset,False
2,2,34274,CHEMBL304053,CC(C)(O)CCC(C[C@H](O)[C@H](Cc1ccccc1F)NC(=O)c1...,smiles_found,CHEMBL372,Homo sapiens,CHEMBL695026,CHEMBL1147552,2004.0,...,F,In vitro oxidative metabolic stability measure...,in vitro oxidative metabolic stability measure...,chembl_hlm_intrinsic,16.5,2.862201,16.500,2.862201,chembl_dataset,False
3,3,35507,CHEMBL68366,CC(C)(F)CC[C@H](C[C@H](O)[C@H](Cc1ccccc1)NC(=O...,smiles_found,CHEMBL372,Homo sapiens,CHEMBL695026,CHEMBL1147552,2004.0,...,F,In vitro oxidative metabolic stability measure...,in vitro oxidative metabolic stability measure...,chembl_hlm_intrinsic,8.0,2.197225,8.000,2.197225,chembl_dataset,False
4,4,39099,CHEMBL303673,O=C(N[C@@H](Cc1ccccc1)[C@@H](O)CC(C(=O)NO)C1CC...,smiles_found,CHEMBL372,Homo sapiens,CHEMBL695026,CHEMBL1147552,2004.0,...,F,In vitro oxidative metabolic stability measure...,in vitro oxidative metabolic stability measure...,chembl_hlm_intrinsic,6.1,1.960095,6.100,1.960095,chembl_dataset,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11697,11697,26316940,CHEMBL5712066,C=CC(=O)Nc1ccc(C(=O)NC2CCN(Cc3ccc(-c4nc5cc[nH]...,smiles_found,CHEMBL612558,ADMET,CHEMBL5712039,CHEMBL5705908,2019.0,...,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic,12.0,2.564949,12.336,2.590467,chembl_dataset,True
11698,11698,26316941,CHEMBL2325741,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2nc[nH]...,smiles_found,CHEMBL612558,ADMET,CHEMBL5712039,CHEMBL5705908,2019.0,...,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic,14.0,2.708050,14.392,2.733848,chembl_dataset,True
11699,11699,26316942,CHEMBL2177390,CC(C)NC[C@@H](C(=O)N1CCN(c2ncnc3c2[C@H](C)C[C@...,smiles_found,CHEMBL612558,ADMET,CHEMBL5712039,CHEMBL5705908,2019.0,...,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic,12.0,2.564949,12.336,2.590467,chembl_dataset,True
11700,11700,26316943,CHEMBL1079175,NC1(c2ccc(-c3nc4ccn5c(=O)[nH]nc5c4cc3-c3ccccc3...,smiles_found,CHEMBL612558,ADMET,CHEMBL5712039,CHEMBL5705908,2019.0,...,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic,1.0,0.693147,1.028,0.707050,chembl_dataset,True
11701,11701,26316944,CHEMBL4795065,C=CC(=O)Nc1ccc2[nH]c(=O)n(C3CCN(Cc4ccc(-c5nc6c...,smiles_found,CHEMBL612558,ADMET,CHEMBL5712039,CHEMBL5705908,2019.0,...,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic,5.0,1.791759,5.140,1.814825,chembl_dataset,True

In [14]:
combined_df = pd.concat([df_fang, df_openadmet_polaris, df_openadmet_expansion, df_chembl], ignore_index=True)

In [15]:
combined_df

,Unnamed: 0,SMILES,LOG HLM_CLint (mL/min/kg),hlm_value_unscaled,hlm_value_unscaled_log1p,hlm_value_scaled,hlm_value_scaled_log1p,dataset,data_year,mol_id,...,standard_type,standard_relation,standard_value,standard_units,data_validity_comment,activity_comment,assay_type,assay_description,classification_text,classification_bucket
0,0,CNc1cc(Nc2cccn(-c3ccccn3)c2=O)nn2c(C(=O)N[C@@H...,0.675687,4.739,1.747285,4.739,1.747285,fang_dataset,2023.0,fang_1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,CCOc1cc2nn(CCC(C)(C)O)cc2cc1NC(=O)c1cccc(C(F)F)n1,0.675687,4.739,1.747285,4.739,1.747285,fang_dataset,2023.0,fang_2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,CN(c1ncc(F)cn1)[C@H]1CCCNC1,0.675687,4.739,1.747285,4.739,1.747285,fang_dataset,2023.0,fang_3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,CC(C)(Oc1ccc(-c2cnc(N)c(-c3ccc(Cl)cc3)c2)cc1)C...,0.675687,4.739,1.747285,4.739,1.747285,fang_dataset,2023.0,fang_4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,CC(C)(O)CCn1cc2cc(NC(=O)c3cccc(C(F)(F)F)n3)c(C...,0.996380,9.917,2.390321,9.917,2.390321,fang_dataset,2023.0,fang_5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18946,11697,C=CC(=O)Nc1ccc(C(=O)NC2CCN(Cc3ccc(-c4nc5cc[nH]...,NaN,12.000,2.564949,12.336,2.590467,chembl_dataset,2019.0,CHEMBL5712066,...,CL,=,12.0,mL.min-1.g-1,NaN,NaN,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic
18947,11698,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2nc[nH]...,NaN,14.000,2.708050,14.392,2.733848,chembl_dataset,2019.0,CHEMBL2325741,...,CL,=,14.0,mL.min-1.g-1,NaN,NaN,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic
18948,11699,CC(C)NC[C@@H](C(=O)N1CCN(c2ncnc3c2[C@H](C)C[C@...,NaN,12.000,2.564949,12.336,2.590467,chembl_dataset,2019.0,CHEMBL2177390,...,CL,=,12.0,mL.min-1.g-1,NaN,NaN,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic
18949,11700,NC1(c2ccc(-c3nc4ccn5c(=O)[nH]nc5c4cc3-c3ccccc3...,NaN,1.000,0.693147,1.028,0.707050,chembl_dataset,2019.0,CHEMBL1079175,...,CL,=,1.0,mL.min-1.g-1,NaN,NaN,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic
18950,11701,C=CC(=O)Nc1ccc2[nH]c(=O)n(C3CCN(Cc4ccc(-c5nc6c...,NaN,5.000,1.791759,5.140,1.814825,chembl_dataset,2019.0,CHEMBL4795065,...,CL,=,5.0,mL.min-1.g-1,NaN,NaN,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic

In [16]:
combined_df_filtered = combined_df[["mol_id", "SMILES", "hlm_value_unscaled", "hlm_value_unscaled_log1p", "hlm_value_scaled", "hlm_value_scaled_log1p", "dataset", "scaling_was_applied"]]

In [17]:
combined_df_filtered

,mol_id,SMILES,hlm_value_unscaled,hlm_value_unscaled_log1p,hlm_value_scaled,hlm_value_scaled_log1p,dataset,scaling_was_applied
0,fang_1,CNc1cc(Nc2cccn(-c3ccccn3)c2=O)nn2c(C(=O)N[C@@H...,4.739,1.747285,4.739,1.747285,fang_dataset,False
1,fang_2,CCOc1cc2nn(CCC(C)(C)O)cc2cc1NC(=O)c1cccc(C(F)F)n1,4.739,1.747285,4.739,1.747285,fang_dataset,False
2,fang_3,CN(c1ncc(F)cn1)[C@H]1CCCNC1,4.739,1.747285,4.739,1.747285,fang_dataset,False
3,fang_4,CC(C)(Oc1ccc(-c2cnc(N)c(-c3ccc(Cl)cc3)c2)cc1)C...,4.739,1.747285,4.739,1.747285,fang_dataset,False
4,fang_5,CC(C)(O)CCn1cc2cc(NC(=O)c3cccc(C(F)(F)F)n3)c(C...,9.917,2.390321,9.917,2.390321,fang_dataset,False
...,...,...,...,...,...,...,...,...
18946,CHEMBL5712066,C=CC(=O)Nc1ccc(C(=O)NC2CCN(Cc3ccc(-c4nc5cc[nH]...,12.000,2.564949,12.336,2.590467,chembl_dataset,True
18947,CHEMBL2325741,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2nc[nH]...,14.000,2.708050,14.392,2.733848,chembl_dataset,True
18948,CHEMBL2177390,CC(C)NC[C@@H](C(=O)N1CCN(c2ncnc3c2[C@H](C)C[C@...,12.000,2.564949,12.336,2.590467,chembl_dataset,True
18949,CHEMBL1079175,NC1(c2ccc(-c3nc4ccn5c(=O)[nH]nc5c4cc3-c3ccccc3...,1.000,0.693147,1.028,0.707050,chembl_dataset,True
18950,CHEMBL4795065,C=CC(=O)Nc1ccc2[nH]c(=O)n(C3CCN(Cc4ccc(-c5nc6c...,5.000,1.791759,5.140,1.814825,chembl_dataset,True

In [18]:
combined_df_filtered.to_csv("combined_datasets/combined_dataset_training.csv")

In [19]:
mask = (
    combined_df_filtered["scaling_was_applied"]
    .astype(str)
    .str.strip()
    .str.lower()
    .eq("false")
)

combined_df_filtered_safe_data = combined_df_filtered.loc[mask]

In [20]:
combined_df_filtered_safe_data

,mol_id,SMILES,hlm_value_unscaled,hlm_value_unscaled_log1p,hlm_value_scaled,hlm_value_scaled_log1p,dataset,scaling_was_applied
0,fang_1,CNc1cc(Nc2cccn(-c3ccccn3)c2=O)nn2c(C(=O)N[C@@H...,4.739,1.747285,4.739,1.747285,fang_dataset,False
1,fang_2,CCOc1cc2nn(CCC(C)(C)O)cc2cc1NC(=O)c1cccc(C(F)F)n1,4.739,1.747285,4.739,1.747285,fang_dataset,False
2,fang_3,CN(c1ncc(F)cn1)[C@H]1CCCNC1,4.739,1.747285,4.739,1.747285,fang_dataset,False
3,fang_4,CC(C)(Oc1ccc(-c2cnc(N)c(-c3ccc(Cl)cc3)c2)cc1)C...,4.739,1.747285,4.739,1.747285,fang_dataset,False
4,fang_5,CC(C)(O)CCn1cc2cc(NC(=O)c3cccc(C(F)(F)F)n3)c(C...,9.917,2.390321,9.917,2.390321,fang_dataset,False
...,...,...,...,...,...,...,...,...
18844,CHEMBL51,O=C(c1ccc(F)cc1)C1CCN(CCn2c(=O)[nH]c3ccccc3c2=...,17.300,2.906901,17.300,2.906901,chembl_dataset,False
18847,CHEMBL5647419,O=C1Nc2ccccc2/C1=C1/Nc2ccc(C(=O)NCC3CCN(C(=O)C...,95.530,4.569854,95.530,4.569854,chembl_dataset,False
18848,CHEMBL1276127,O=C1Nc2ccccc2/C1=C1/Nc2ccccc2C1=O,70.190,4.265352,70.190,4.265352,chembl_dataset,False
18849,CHEMBL5095043,C[C@@H](COCCC(=O)N1CCN(c2ncc(C(F)(F)F)cn2)CC1)...,23.200,3.186353,23.200,3.186353,chembl_dataset,False
18850,CHEMBL5639789,O=C(CCOC[C@@H]1CCN1c1cn[nH]c(=O)c1C(F)(F)F)N1C...,19.800,3.034953,19.800,3.034953,chembl_dataset,False

In [21]:
combined_df_filtered_safe_data["dataset"].unique()

array(['fang_dataset', 'openadmet_expansion_train', 'chembl_dataset'],
      dtype=object)

In [22]:
combined_df_filtered_safe_data.to_csv("combined_datasets/combined_dataset_training_no_scaling.csv")

In [23]:
combined_df_expansion = combined_df_filtered.loc[combined_df_filtered["dataset"] == "openadmet_expansion_train"]

In [24]:
combined_df_expansion.to_csv("combined_datasets/openadmet_expansion_only_training.csv")