In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("raw_datasets/chembl/chembl_hlm_intrinsic.csv")

In [3]:
df

,activity_id,molecule_chembl_id,smiles,structure_status,target_chembl_id,target_name,assay_chembl_id,document_chembl_id,data_year,standard_type,standard_relation,standard_value,standard_units,data_validity_comment,activity_comment,assay_type,assay_description,classification_text,classification_bucket
0,33031,CHEMBL306457,NC(=O)C(C[C@H](O)[C@H](Cc1ccccc1)NC(=O)c1cnc2c...,smiles_found,CHEMBL372,Homo sapiens,CHEMBL695026,CHEMBL1147552,2004.0,CL,=,47.7,mL.min-1.kg-1,NaN,NaN,F,In vitro oxidative metabolic stability measure...,in vitro oxidative metabolic stability measure...,chembl_hlm_intrinsic
1,34270,CHEMBL66457,CC(C)(O)CC[C@H](C[C@H](O)[C@H](Cc1ccccc1)NC(=O...,smiles_found,CHEMBL372,Homo sapiens,CHEMBL695026,CHEMBL1147552,2004.0,CL,=,4.9,mL.min-1.kg-1,NaN,NaN,F,In vitro oxidative metabolic stability measure...,in vitro oxidative metabolic stability measure...,chembl_hlm_intrinsic
2,34274,CHEMBL304053,CC(C)(O)CCC(C[C@H](O)[C@H](Cc1ccccc1F)NC(=O)c1...,smiles_found,CHEMBL372,Homo sapiens,CHEMBL695026,CHEMBL1147552,2004.0,CL,=,16.5,mL.min-1.kg-1,NaN,NaN,F,In vitro oxidative metabolic stability measure...,in vitro oxidative metabolic stability measure...,chembl_hlm_intrinsic
3,35507,CHEMBL68366,CC(C)(F)CC[C@H](C[C@H](O)[C@H](Cc1ccccc1)NC(=O...,smiles_found,CHEMBL372,Homo sapiens,CHEMBL695026,CHEMBL1147552,2004.0,CL,=,8.0,mL.min-1.kg-1,NaN,NaN,F,In vitro oxidative metabolic stability measure...,in vitro oxidative metabolic stability measure...,chembl_hlm_intrinsic
4,39099,CHEMBL303673,O=C(N[C@@H](Cc1ccccc1)[C@@H](O)CC(C(=O)NO)C1CC...,smiles_found,CHEMBL372,Homo sapiens,CHEMBL695026,CHEMBL1147552,2004.0,CL,=,6.1,mL.min-1.kg-1,NaN,NaN,F,In vitro oxidative metabolic stability measure...,in vitro oxidative metabolic stability measure...,chembl_hlm_intrinsic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12132,26316940,CHEMBL5712066,C=CC(=O)Nc1ccc(C(=O)NC2CCN(Cc3ccc(-c4nc5cc[nH]...,smiles_found,CHEMBL612558,ADMET,CHEMBL5712039,CHEMBL5705908,2019.0,CL,=,12.0,mL.min-1.g-1,NaN,NaN,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic
12133,26316941,CHEMBL2325741,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2nc[nH]...,smiles_found,CHEMBL612558,ADMET,CHEMBL5712039,CHEMBL5705908,2019.0,CL,=,14.0,mL.min-1.g-1,NaN,NaN,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic
12134,26316942,CHEMBL2177390,CC(C)NC[C@@H](C(=O)N1CCN(c2ncnc3c2[C@H](C)C[C@...,smiles_found,CHEMBL612558,ADMET,CHEMBL5712039,CHEMBL5705908,2019.0,CL,=,12.0,mL.min-1.g-1,NaN,NaN,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic
12135,26316943,CHEMBL1079175,NC1(c2ccc(-c3nc4ccn5c(=O)[nH]nc5c4cc3-c3ccccc3...,smiles_found,CHEMBL612558,ADMET,CHEMBL5712039,CHEMBL5705908,2019.0,CL,=,1.0,mL.min-1.g-1,NaN,NaN,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic
12136,26316944,CHEMBL4795065,C=CC(=O)Nc1ccc2[nH]c(=O)n(C3CCN(Cc4ccc(-c5nc6c...,smiles_found,CHEMBL612558,ADMET,CHEMBL5712039,CHEMBL5705908,2019.0,CL,=,5.0,mL.min-1.g-1,NaN,NaN,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic

#### Certain assays mention values outside of typical range showing very high HLM CLint values. For this dataset I remove them. Depending on the procedure they can also be kept, if the reason that they are outside of typical range is related to the compounds themselves and not errors from the experimental or procedual side of things

In [4]:
df["data_validity_comment"].unique()

array([nan, 'Outside typical range'], dtype=object)

In [5]:
df_inside_range = df[df["data_validity_comment"].isna()]

In [6]:
df_inside_range

,activity_id,molecule_chembl_id,smiles,structure_status,target_chembl_id,target_name,assay_chembl_id,document_chembl_id,data_year,standard_type,standard_relation,standard_value,standard_units,data_validity_comment,activity_comment,assay_type,assay_description,classification_text,classification_bucket
0,33031,CHEMBL306457,NC(=O)C(C[C@H](O)[C@H](Cc1ccccc1)NC(=O)c1cnc2c...,smiles_found,CHEMBL372,Homo sapiens,CHEMBL695026,CHEMBL1147552,2004.0,CL,=,47.7,mL.min-1.kg-1,NaN,NaN,F,In vitro oxidative metabolic stability measure...,in vitro oxidative metabolic stability measure...,chembl_hlm_intrinsic
1,34270,CHEMBL66457,CC(C)(O)CC[C@H](C[C@H](O)[C@H](Cc1ccccc1)NC(=O...,smiles_found,CHEMBL372,Homo sapiens,CHEMBL695026,CHEMBL1147552,2004.0,CL,=,4.9,mL.min-1.kg-1,NaN,NaN,F,In vitro oxidative metabolic stability measure...,in vitro oxidative metabolic stability measure...,chembl_hlm_intrinsic
2,34274,CHEMBL304053,CC(C)(O)CCC(C[C@H](O)[C@H](Cc1ccccc1F)NC(=O)c1...,smiles_found,CHEMBL372,Homo sapiens,CHEMBL695026,CHEMBL1147552,2004.0,CL,=,16.5,mL.min-1.kg-1,NaN,NaN,F,In vitro oxidative metabolic stability measure...,in vitro oxidative metabolic stability measure...,chembl_hlm_intrinsic
3,35507,CHEMBL68366,CC(C)(F)CC[C@H](C[C@H](O)[C@H](Cc1ccccc1)NC(=O...,smiles_found,CHEMBL372,Homo sapiens,CHEMBL695026,CHEMBL1147552,2004.0,CL,=,8.0,mL.min-1.kg-1,NaN,NaN,F,In vitro oxidative metabolic stability measure...,in vitro oxidative metabolic stability measure...,chembl_hlm_intrinsic
4,39099,CHEMBL303673,O=C(N[C@@H](Cc1ccccc1)[C@@H](O)CC(C(=O)NO)C1CC...,smiles_found,CHEMBL372,Homo sapiens,CHEMBL695026,CHEMBL1147552,2004.0,CL,=,6.1,mL.min-1.kg-1,NaN,NaN,F,In vitro oxidative metabolic stability measure...,in vitro oxidative metabolic stability measure...,chembl_hlm_intrinsic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12132,26316940,CHEMBL5712066,C=CC(=O)Nc1ccc(C(=O)NC2CCN(Cc3ccc(-c4nc5cc[nH]...,smiles_found,CHEMBL612558,ADMET,CHEMBL5712039,CHEMBL5705908,2019.0,CL,=,12.0,mL.min-1.g-1,NaN,NaN,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic
12133,26316941,CHEMBL2325741,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2nc[nH]...,smiles_found,CHEMBL612558,ADMET,CHEMBL5712039,CHEMBL5705908,2019.0,CL,=,14.0,mL.min-1.g-1,NaN,NaN,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic
12134,26316942,CHEMBL2177390,CC(C)NC[C@@H](C(=O)N1CCN(c2ncnc3c2[C@H](C)C[C@...,smiles_found,CHEMBL612558,ADMET,CHEMBL5712039,CHEMBL5705908,2019.0,CL,=,12.0,mL.min-1.g-1,NaN,NaN,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic
12135,26316943,CHEMBL1079175,NC1(c2ccc(-c3nc4ccn5c(=O)[nH]nc5c4cc3-c3ccccc3...,smiles_found,CHEMBL612558,ADMET,CHEMBL5712039,CHEMBL5705908,2019.0,CL,=,1.0,mL.min-1.g-1,NaN,NaN,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic
12136,26316944,CHEMBL4795065,C=CC(=O)Nc1ccc2[nH]c(=O)n(C3CCN(Cc4ccc(-c5nc6c...,smiles_found,CHEMBL612558,ADMET,CHEMBL5712039,CHEMBL5705908,2019.0,CL,=,5.0,mL.min-1.g-1,NaN,NaN,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic

The ChEMBL retrieved data contains values with various units. While we retain the applicable mL.min-1.kg-1 and mL.min-1.g-1 which we need to scale we drop the remainder, including ml/min.mg due to it only having 5 data points and min.kg/L having 4 data points due to them requiring a separate scaling algorithm most likely

In [7]:
df_inside_range["standard_units"].unique()

array(['mL.min-1.kg-1', 'mL.min-1.g-1', 'nmol/mg/min', 'nM/min/mg',
       'ml/min.mg', 'mg/ml/g', 'min.kg/L', 'hr.Kg/L', 'uL/ml/kg',
       'uL/ml.millig', 'ug ml-1', 'ug/min/mg', 'uL/min', 'ug/min',
       'L/min'], dtype=object)

In [8]:
df_inside_range["standard_units"].value_counts().reindex([
    'mL.min-1.kg-1', 'mL.min-1.g-1', 'nmol/mg/min', 'nM/min/mg',
    'ml/min.mg', 'mg/ml/g', 'min.kg/L', 'hr.Kg/L', 'uL/ml/kg',
    'uL/ml.millig', 'ug ml-1', 'ug/min/mg', 'uL/min', 'ug/min',
    'L/min'
], fill_value=0)

standard_units
mL.min-1.kg-1    2843
mL.min-1.g-1     8859
nmol/mg/min        10
nM/min/mg           1
ml/min.mg           5
mg/ml/g             1
min.kg/L            4
hr.Kg/L            33
uL/ml/kg           21
uL/ml.millig       10
ug ml-1            36
ug/min/mg           9
uL/min             17
ug/min              2
L/min              69
Name: count, dtype: int64

In [9]:
df_inside_range = df_inside_range[
    df_inside_range["standard_units"].isin([
        "mL.min-1.kg-1",
        "mL.min-1.g-1",
    ])
].reset_index(drop=True)

In [10]:
df_inside_range

,activity_id,molecule_chembl_id,smiles,structure_status,target_chembl_id,target_name,assay_chembl_id,document_chembl_id,data_year,standard_type,standard_relation,standard_value,standard_units,data_validity_comment,activity_comment,assay_type,assay_description,classification_text,classification_bucket
0,33031,CHEMBL306457,NC(=O)C(C[C@H](O)[C@H](Cc1ccccc1)NC(=O)c1cnc2c...,smiles_found,CHEMBL372,Homo sapiens,CHEMBL695026,CHEMBL1147552,2004.0,CL,=,47.7,mL.min-1.kg-1,NaN,NaN,F,In vitro oxidative metabolic stability measure...,in vitro oxidative metabolic stability measure...,chembl_hlm_intrinsic
1,34270,CHEMBL66457,CC(C)(O)CC[C@H](C[C@H](O)[C@H](Cc1ccccc1)NC(=O...,smiles_found,CHEMBL372,Homo sapiens,CHEMBL695026,CHEMBL1147552,2004.0,CL,=,4.9,mL.min-1.kg-1,NaN,NaN,F,In vitro oxidative metabolic stability measure...,in vitro oxidative metabolic stability measure...,chembl_hlm_intrinsic
2,34274,CHEMBL304053,CC(C)(O)CCC(C[C@H](O)[C@H](Cc1ccccc1F)NC(=O)c1...,smiles_found,CHEMBL372,Homo sapiens,CHEMBL695026,CHEMBL1147552,2004.0,CL,=,16.5,mL.min-1.kg-1,NaN,NaN,F,In vitro oxidative metabolic stability measure...,in vitro oxidative metabolic stability measure...,chembl_hlm_intrinsic
3,35507,CHEMBL68366,CC(C)(F)CC[C@H](C[C@H](O)[C@H](Cc1ccccc1)NC(=O...,smiles_found,CHEMBL372,Homo sapiens,CHEMBL695026,CHEMBL1147552,2004.0,CL,=,8.0,mL.min-1.kg-1,NaN,NaN,F,In vitro oxidative metabolic stability measure...,in vitro oxidative metabolic stability measure...,chembl_hlm_intrinsic
4,39099,CHEMBL303673,O=C(N[C@@H](Cc1ccccc1)[C@@H](O)CC(C(=O)NO)C1CC...,smiles_found,CHEMBL372,Homo sapiens,CHEMBL695026,CHEMBL1147552,2004.0,CL,=,6.1,mL.min-1.kg-1,NaN,NaN,F,In vitro oxidative metabolic stability measure...,in vitro oxidative metabolic stability measure...,chembl_hlm_intrinsic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11697,26316940,CHEMBL5712066,C=CC(=O)Nc1ccc(C(=O)NC2CCN(Cc3ccc(-c4nc5cc[nH]...,smiles_found,CHEMBL612558,ADMET,CHEMBL5712039,CHEMBL5705908,2019.0,CL,=,12.0,mL.min-1.g-1,NaN,NaN,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic
11698,26316941,CHEMBL2325741,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2nc[nH]...,smiles_found,CHEMBL612558,ADMET,CHEMBL5712039,CHEMBL5705908,2019.0,CL,=,14.0,mL.min-1.g-1,NaN,NaN,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic
11699,26316942,CHEMBL2177390,CC(C)NC[C@@H](C(=O)N1CCN(c2ncnc3c2[C@H](C)C[C@...,smiles_found,CHEMBL612558,ADMET,CHEMBL5712039,CHEMBL5705908,2019.0,CL,=,12.0,mL.min-1.g-1,NaN,NaN,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic
11700,26316943,CHEMBL1079175,NC1(c2ccc(-c3nc4ccn5c(=O)[nH]nc5c4cc3-c3ccccc3...,smiles_found,CHEMBL612558,ADMET,CHEMBL5712039,CHEMBL5705908,2019.0,CL,=,1.0,mL.min-1.g-1,NaN,NaN,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic
11701,26316944,CHEMBL4795065,C=CC(=O)Nc1ccc2[nH]c(=O)n(C3CCN(Cc4ccc(-c5nc6c...,smiles_found,CHEMBL612558,ADMET,CHEMBL5712039,CHEMBL5705908,2019.0,CL,=,5.0,mL.min-1.g-1,NaN,NaN,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic

We also need to drop the 0 value data points due to them influencing log10 and with the OpenADMET not having 0 cases

In [11]:
df_inside_range

,activity_id,molecule_chembl_id,smiles,structure_status,target_chembl_id,target_name,assay_chembl_id,document_chembl_id,data_year,standard_type,standard_relation,standard_value,standard_units,data_validity_comment,activity_comment,assay_type,assay_description,classification_text,classification_bucket
0,33031,CHEMBL306457,NC(=O)C(C[C@H](O)[C@H](Cc1ccccc1)NC(=O)c1cnc2c...,smiles_found,CHEMBL372,Homo sapiens,CHEMBL695026,CHEMBL1147552,2004.0,CL,=,47.7,mL.min-1.kg-1,NaN,NaN,F,In vitro oxidative metabolic stability measure...,in vitro oxidative metabolic stability measure...,chembl_hlm_intrinsic
1,34270,CHEMBL66457,CC(C)(O)CC[C@H](C[C@H](O)[C@H](Cc1ccccc1)NC(=O...,smiles_found,CHEMBL372,Homo sapiens,CHEMBL695026,CHEMBL1147552,2004.0,CL,=,4.9,mL.min-1.kg-1,NaN,NaN,F,In vitro oxidative metabolic stability measure...,in vitro oxidative metabolic stability measure...,chembl_hlm_intrinsic
2,34274,CHEMBL304053,CC(C)(O)CCC(C[C@H](O)[C@H](Cc1ccccc1F)NC(=O)c1...,smiles_found,CHEMBL372,Homo sapiens,CHEMBL695026,CHEMBL1147552,2004.0,CL,=,16.5,mL.min-1.kg-1,NaN,NaN,F,In vitro oxidative metabolic stability measure...,in vitro oxidative metabolic stability measure...,chembl_hlm_intrinsic
3,35507,CHEMBL68366,CC(C)(F)CC[C@H](C[C@H](O)[C@H](Cc1ccccc1)NC(=O...,smiles_found,CHEMBL372,Homo sapiens,CHEMBL695026,CHEMBL1147552,2004.0,CL,=,8.0,mL.min-1.kg-1,NaN,NaN,F,In vitro oxidative metabolic stability measure...,in vitro oxidative metabolic stability measure...,chembl_hlm_intrinsic
4,39099,CHEMBL303673,O=C(N[C@@H](Cc1ccccc1)[C@@H](O)CC(C(=O)NO)C1CC...,smiles_found,CHEMBL372,Homo sapiens,CHEMBL695026,CHEMBL1147552,2004.0,CL,=,6.1,mL.min-1.kg-1,NaN,NaN,F,In vitro oxidative metabolic stability measure...,in vitro oxidative metabolic stability measure...,chembl_hlm_intrinsic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11697,26316940,CHEMBL5712066,C=CC(=O)Nc1ccc(C(=O)NC2CCN(Cc3ccc(-c4nc5cc[nH]...,smiles_found,CHEMBL612558,ADMET,CHEMBL5712039,CHEMBL5705908,2019.0,CL,=,12.0,mL.min-1.g-1,NaN,NaN,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic
11698,26316941,CHEMBL2325741,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2nc[nH]...,smiles_found,CHEMBL612558,ADMET,CHEMBL5712039,CHEMBL5705908,2019.0,CL,=,14.0,mL.min-1.g-1,NaN,NaN,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic
11699,26316942,CHEMBL2177390,CC(C)NC[C@@H](C(=O)N1CCN(c2ncnc3c2[C@H](C)C[C@...,smiles_found,CHEMBL612558,ADMET,CHEMBL5712039,CHEMBL5705908,2019.0,CL,=,12.0,mL.min-1.g-1,NaN,NaN,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic
11700,26316943,CHEMBL1079175,NC1(c2ccc(-c3nc4ccn5c(=O)[nH]nc5c4cc3-c3ccccc3...,smiles_found,CHEMBL612558,ADMET,CHEMBL5712039,CHEMBL5705908,2019.0,CL,=,1.0,mL.min-1.g-1,NaN,NaN,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic
11701,26316944,CHEMBL4795065,C=CC(=O)Nc1ccc2[nH]c(=O)n(C3CCN(Cc4ccc(-c5nc6c...,smiles_found,CHEMBL612558,ADMET,CHEMBL5712039,CHEMBL5705908,2019.0,CL,=,5.0,mL.min-1.g-1,NaN,NaN,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic

In [12]:
df_inside_range = df_inside_range[df_inside_range["document_chembl_id"] != "CHEMBL5442168"]

In [13]:
df_inside_range["target_name"].unique()

array(['Homo sapiens', 'ADMET', 'Liver microsomes', 'Liver',
       'Liver microsome', 'Liver carboxylesterase 1',
       'UDP-glucuronosyltransferase 1A1',
       'UDP-glucuronosyltransferases (UGTs)', 'Cytochrome P450 2D6',
       'Cytochrome P450 3A4'], dtype=object)

In [14]:
df_inside_range

,activity_id,molecule_chembl_id,smiles,structure_status,target_chembl_id,target_name,assay_chembl_id,document_chembl_id,data_year,standard_type,standard_relation,standard_value,standard_units,data_validity_comment,activity_comment,assay_type,assay_description,classification_text,classification_bucket
0,33031,CHEMBL306457,NC(=O)C(C[C@H](O)[C@H](Cc1ccccc1)NC(=O)c1cnc2c...,smiles_found,CHEMBL372,Homo sapiens,CHEMBL695026,CHEMBL1147552,2004.0,CL,=,47.7,mL.min-1.kg-1,NaN,NaN,F,In vitro oxidative metabolic stability measure...,in vitro oxidative metabolic stability measure...,chembl_hlm_intrinsic
1,34270,CHEMBL66457,CC(C)(O)CC[C@H](C[C@H](O)[C@H](Cc1ccccc1)NC(=O...,smiles_found,CHEMBL372,Homo sapiens,CHEMBL695026,CHEMBL1147552,2004.0,CL,=,4.9,mL.min-1.kg-1,NaN,NaN,F,In vitro oxidative metabolic stability measure...,in vitro oxidative metabolic stability measure...,chembl_hlm_intrinsic
2,34274,CHEMBL304053,CC(C)(O)CCC(C[C@H](O)[C@H](Cc1ccccc1F)NC(=O)c1...,smiles_found,CHEMBL372,Homo sapiens,CHEMBL695026,CHEMBL1147552,2004.0,CL,=,16.5,mL.min-1.kg-1,NaN,NaN,F,In vitro oxidative metabolic stability measure...,in vitro oxidative metabolic stability measure...,chembl_hlm_intrinsic
3,35507,CHEMBL68366,CC(C)(F)CC[C@H](C[C@H](O)[C@H](Cc1ccccc1)NC(=O...,smiles_found,CHEMBL372,Homo sapiens,CHEMBL695026,CHEMBL1147552,2004.0,CL,=,8.0,mL.min-1.kg-1,NaN,NaN,F,In vitro oxidative metabolic stability measure...,in vitro oxidative metabolic stability measure...,chembl_hlm_intrinsic
4,39099,CHEMBL303673,O=C(N[C@@H](Cc1ccccc1)[C@@H](O)CC(C(=O)NO)C1CC...,smiles_found,CHEMBL372,Homo sapiens,CHEMBL695026,CHEMBL1147552,2004.0,CL,=,6.1,mL.min-1.kg-1,NaN,NaN,F,In vitro oxidative metabolic stability measure...,in vitro oxidative metabolic stability measure...,chembl_hlm_intrinsic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11697,26316940,CHEMBL5712066,C=CC(=O)Nc1ccc(C(=O)NC2CCN(Cc3ccc(-c4nc5cc[nH]...,smiles_found,CHEMBL612558,ADMET,CHEMBL5712039,CHEMBL5705908,2019.0,CL,=,12.0,mL.min-1.g-1,NaN,NaN,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic
11698,26316941,CHEMBL2325741,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2nc[nH]...,smiles_found,CHEMBL612558,ADMET,CHEMBL5712039,CHEMBL5705908,2019.0,CL,=,14.0,mL.min-1.g-1,NaN,NaN,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic
11699,26316942,CHEMBL2177390,CC(C)NC[C@@H](C(=O)N1CCN(c2ncnc3c2[C@H](C)C[C@...,smiles_found,CHEMBL612558,ADMET,CHEMBL5712039,CHEMBL5705908,2019.0,CL,=,12.0,mL.min-1.g-1,NaN,NaN,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic
11700,26316943,CHEMBL1079175,NC1(c2ccc(-c3nc4ccn5c(=O)[nH]nc5c4cc3-c3ccccc3...,smiles_found,CHEMBL612558,ADMET,CHEMBL5712039,CHEMBL5705908,2019.0,CL,=,1.0,mL.min-1.g-1,NaN,NaN,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic
11701,26316944,CHEMBL4795065,C=CC(=O)Nc1ccc2[nH]c(=O)n(C3CCN(Cc4ccc(-c5nc6c...,smiles_found,CHEMBL612558,ADMET,CHEMBL5712039,CHEMBL5705908,2019.0,CL,=,5.0,mL.min-1.g-1,NaN,NaN,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic

In [15]:
def clip_and_log_transform(y: np.ndarray):
    """
    Clip to a detection limit and transform to log10 scale.
    Parameters
    ----------
    y : np.ndarray
        The array to be clipped and transformed.
    """
    y = np.clip(y, a_min=0, a_max=None)
    return np.log10(y + 1)

In [16]:
df_inside_range

,activity_id,molecule_chembl_id,smiles,structure_status,target_chembl_id,target_name,assay_chembl_id,document_chembl_id,data_year,standard_type,standard_relation,standard_value,standard_units,data_validity_comment,activity_comment,assay_type,assay_description,classification_text,classification_bucket
0,33031,CHEMBL306457,NC(=O)C(C[C@H](O)[C@H](Cc1ccccc1)NC(=O)c1cnc2c...,smiles_found,CHEMBL372,Homo sapiens,CHEMBL695026,CHEMBL1147552,2004.0,CL,=,47.7,mL.min-1.kg-1,NaN,NaN,F,In vitro oxidative metabolic stability measure...,in vitro oxidative metabolic stability measure...,chembl_hlm_intrinsic
1,34270,CHEMBL66457,CC(C)(O)CC[C@H](C[C@H](O)[C@H](Cc1ccccc1)NC(=O...,smiles_found,CHEMBL372,Homo sapiens,CHEMBL695026,CHEMBL1147552,2004.0,CL,=,4.9,mL.min-1.kg-1,NaN,NaN,F,In vitro oxidative metabolic stability measure...,in vitro oxidative metabolic stability measure...,chembl_hlm_intrinsic
2,34274,CHEMBL304053,CC(C)(O)CCC(C[C@H](O)[C@H](Cc1ccccc1F)NC(=O)c1...,smiles_found,CHEMBL372,Homo sapiens,CHEMBL695026,CHEMBL1147552,2004.0,CL,=,16.5,mL.min-1.kg-1,NaN,NaN,F,In vitro oxidative metabolic stability measure...,in vitro oxidative metabolic stability measure...,chembl_hlm_intrinsic
3,35507,CHEMBL68366,CC(C)(F)CC[C@H](C[C@H](O)[C@H](Cc1ccccc1)NC(=O...,smiles_found,CHEMBL372,Homo sapiens,CHEMBL695026,CHEMBL1147552,2004.0,CL,=,8.0,mL.min-1.kg-1,NaN,NaN,F,In vitro oxidative metabolic stability measure...,in vitro oxidative metabolic stability measure...,chembl_hlm_intrinsic
4,39099,CHEMBL303673,O=C(N[C@@H](Cc1ccccc1)[C@@H](O)CC(C(=O)NO)C1CC...,smiles_found,CHEMBL372,Homo sapiens,CHEMBL695026,CHEMBL1147552,2004.0,CL,=,6.1,mL.min-1.kg-1,NaN,NaN,F,In vitro oxidative metabolic stability measure...,in vitro oxidative metabolic stability measure...,chembl_hlm_intrinsic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11697,26316940,CHEMBL5712066,C=CC(=O)Nc1ccc(C(=O)NC2CCN(Cc3ccc(-c4nc5cc[nH]...,smiles_found,CHEMBL612558,ADMET,CHEMBL5712039,CHEMBL5705908,2019.0,CL,=,12.0,mL.min-1.g-1,NaN,NaN,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic
11698,26316941,CHEMBL2325741,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2nc[nH]...,smiles_found,CHEMBL612558,ADMET,CHEMBL5712039,CHEMBL5705908,2019.0,CL,=,14.0,mL.min-1.g-1,NaN,NaN,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic
11699,26316942,CHEMBL2177390,CC(C)NC[C@@H](C(=O)N1CCN(c2ncnc3c2[C@H](C)C[C@...,smiles_found,CHEMBL612558,ADMET,CHEMBL5712039,CHEMBL5705908,2019.0,CL,=,12.0,mL.min-1.g-1,NaN,NaN,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic
11700,26316943,CHEMBL1079175,NC1(c2ccc(-c3nc4ccn5c(=O)[nH]nc5c4cc3-c3ccccc3...,smiles_found,CHEMBL612558,ADMET,CHEMBL5712039,CHEMBL5705908,2019.0,CL,=,1.0,mL.min-1.g-1,NaN,NaN,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic
11701,26316944,CHEMBL4795065,C=CC(=O)Nc1ccc2[nH]c(=O)n(C3CCN(Cc4ccc(-c5nc6c...,smiles_found,CHEMBL612558,ADMET,CHEMBL5712039,CHEMBL5705908,2019.0,CL,=,5.0,mL.min-1.g-1,NaN,NaN,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic

In [17]:
import numpy as np

df_inside_range["hlm_value_unscaled"] = df_inside_range["standard_value"]

df_inside_range["hlm_value_scaled_high"] = np.where(
    df_inside_range["standard_units"] == "mL.min-1.g-1",
    df_inside_range["standard_value"] * 1.028,
    df_inside_range["standard_value"]
)

df_inside_range["hlm_value_scaled_low"] = np.where(
    df_inside_range["standard_units"] == "mL.min-1.g-1",
    df_inside_range["standard_value"] * 0.840,
    df_inside_range["standard_value"]
)

C:\Users\talag\AppData\Local\Temp\ipykernel_34132\3023677376.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_inside_range["hlm_value_unscaled"] = df_inside_range["standard_value"]
C:\Users\talag\AppData\Local\Temp\ipykernel_34132\3023677376.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_inside_range["hlm_value_scaled_high"] = np.where(
C:\Users\talag\AppData\Local\Temp\ipykernel_34132\3023677376.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_inside_range["hlm_value_scaled_low"] = np.where(

In [18]:
df_inside_range

,activity_id,molecule_chembl_id,smiles,structure_status,target_chembl_id,target_name,assay_chembl_id,document_chembl_id,data_year,standard_type,...,standard_units,data_validity_comment,activity_comment,assay_type,assay_description,classification_text,classification_bucket,hlm_value_unscaled,hlm_value_scaled_high,hlm_value_scaled_low
0,33031,CHEMBL306457,NC(=O)C(C[C@H](O)[C@H](Cc1ccccc1)NC(=O)c1cnc2c...,smiles_found,CHEMBL372,Homo sapiens,CHEMBL695026,CHEMBL1147552,2004.0,CL,...,mL.min-1.kg-1,NaN,NaN,F,In vitro oxidative metabolic stability measure...,in vitro oxidative metabolic stability measure...,chembl_hlm_intrinsic,47.7,47.700,47.70
1,34270,CHEMBL66457,CC(C)(O)CC[C@H](C[C@H](O)[C@H](Cc1ccccc1)NC(=O...,smiles_found,CHEMBL372,Homo sapiens,CHEMBL695026,CHEMBL1147552,2004.0,CL,...,mL.min-1.kg-1,NaN,NaN,F,In vitro oxidative metabolic stability measure...,in vitro oxidative metabolic stability measure...,chembl_hlm_intrinsic,4.9,4.900,4.90
2,34274,CHEMBL304053,CC(C)(O)CCC(C[C@H](O)[C@H](Cc1ccccc1F)NC(=O)c1...,smiles_found,CHEMBL372,Homo sapiens,CHEMBL695026,CHEMBL1147552,2004.0,CL,...,mL.min-1.kg-1,NaN,NaN,F,In vitro oxidative metabolic stability measure...,in vitro oxidative metabolic stability measure...,chembl_hlm_intrinsic,16.5,16.500,16.50
3,35507,CHEMBL68366,CC(C)(F)CC[C@H](C[C@H](O)[C@H](Cc1ccccc1)NC(=O...,smiles_found,CHEMBL372,Homo sapiens,CHEMBL695026,CHEMBL1147552,2004.0,CL,...,mL.min-1.kg-1,NaN,NaN,F,In vitro oxidative metabolic stability measure...,in vitro oxidative metabolic stability measure...,chembl_hlm_intrinsic,8.0,8.000,8.00
4,39099,CHEMBL303673,O=C(N[C@@H](Cc1ccccc1)[C@@H](O)CC(C(=O)NO)C1CC...,smiles_found,CHEMBL372,Homo sapiens,CHEMBL695026,CHEMBL1147552,2004.0,CL,...,mL.min-1.kg-1,NaN,NaN,F,In vitro oxidative metabolic stability measure...,in vitro oxidative metabolic stability measure...,chembl_hlm_intrinsic,6.1,6.100,6.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11697,26316940,CHEMBL5712066,C=CC(=O)Nc1ccc(C(=O)NC2CCN(Cc3ccc(-c4nc5cc[nH]...,smiles_found,CHEMBL612558,ADMET,CHEMBL5712039,CHEMBL5705908,2019.0,CL,...,mL.min-1.g-1,NaN,NaN,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic,12.0,12.336,10.08
11698,26316941,CHEMBL2325741,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2nc[nH]...,smiles_found,CHEMBL612558,ADMET,CHEMBL5712039,CHEMBL5705908,2019.0,CL,...,mL.min-1.g-1,NaN,NaN,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic,14.0,14.392,11.76
11699,26316942,CHEMBL2177390,CC(C)NC[C@@H](C(=O)N1CCN(c2ncnc3c2[C@H](C)C[C@...,smiles_found,CHEMBL612558,ADMET,CHEMBL5712039,CHEMBL5705908,2019.0,CL,...,mL.min-1.g-1,NaN,NaN,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic,12.0,12.336,10.08
11700,26316943,CHEMBL1079175,NC1(c2ccc(-c3nc4ccn5c(=O)[nH]nc5c4cc3-c3ccccc3...,smiles_found,CHEMBL612558,ADMET,CHEMBL5712039,CHEMBL5705908,2019.0,CL,...,mL.min-1.g-1,NaN,NaN,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic,1.0,1.028,0.84
11701,26316944,CHEMBL4795065,C=CC(=O)Nc1ccc2[nH]c(=O)n(C3CCN(Cc4ccc(-c5nc6c...,smiles_found,CHEMBL612558,ADMET,CHEMBL5712039,CHEMBL5705908,2019.0,CL,...,mL.min-1.g-1,NaN,NaN,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic,5.0,5.140,4.20

In [19]:
df_inside_range["hlm_value_unscaled_log10"] = clip_and_log_transform(
    df_inside_range["hlm_value_unscaled"].to_numpy()
)

df_inside_range["hlm_value_scaled_log10_high"] = clip_and_log_transform(
    df_inside_range["hlm_value_scaled_high"].to_numpy()
)

df_inside_range["hlm_value_scaled_log10_low"] = clip_and_log_transform(
    df_inside_range["hlm_value_scaled_low"].to_numpy()
)

C:\Users\talag\AppData\Local\Temp\ipykernel_34132\2485549652.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_inside_range["hlm_value_unscaled_log10"] = clip_and_log_transform(
C:\Users\talag\AppData\Local\Temp\ipykernel_34132\2485549652.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_inside_range["hlm_value_scaled_log10_high"] = clip_and_log_transform(
C:\Users\talag\AppData\Local\Temp\ipykernel_34132\2485549652.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_inside_range["hlm_value_scaled_log10_low"] = clip_and_log_transform(

In [20]:
df_inside_range

,activity_id,molecule_chembl_id,smiles,structure_status,target_chembl_id,target_name,assay_chembl_id,document_chembl_id,data_year,standard_type,...,assay_type,assay_description,classification_text,classification_bucket,hlm_value_unscaled,hlm_value_scaled_high,hlm_value_scaled_low,hlm_value_unscaled_log10,hlm_value_scaled_log10_high,hlm_value_scaled_log10_low
0,33031,CHEMBL306457,NC(=O)C(C[C@H](O)[C@H](Cc1ccccc1)NC(=O)c1cnc2c...,smiles_found,CHEMBL372,Homo sapiens,CHEMBL695026,CHEMBL1147552,2004.0,CL,...,F,In vitro oxidative metabolic stability measure...,in vitro oxidative metabolic stability measure...,chembl_hlm_intrinsic,47.7,47.700,47.70,1.687529,1.687529,1.687529
1,34270,CHEMBL66457,CC(C)(O)CC[C@H](C[C@H](O)[C@H](Cc1ccccc1)NC(=O...,smiles_found,CHEMBL372,Homo sapiens,CHEMBL695026,CHEMBL1147552,2004.0,CL,...,F,In vitro oxidative metabolic stability measure...,in vitro oxidative metabolic stability measure...,chembl_hlm_intrinsic,4.9,4.900,4.90,0.770852,0.770852,0.770852
2,34274,CHEMBL304053,CC(C)(O)CCC(C[C@H](O)[C@H](Cc1ccccc1F)NC(=O)c1...,smiles_found,CHEMBL372,Homo sapiens,CHEMBL695026,CHEMBL1147552,2004.0,CL,...,F,In vitro oxidative metabolic stability measure...,in vitro oxidative metabolic stability measure...,chembl_hlm_intrinsic,16.5,16.500,16.50,1.243038,1.243038,1.243038
3,35507,CHEMBL68366,CC(C)(F)CC[C@H](C[C@H](O)[C@H](Cc1ccccc1)NC(=O...,smiles_found,CHEMBL372,Homo sapiens,CHEMBL695026,CHEMBL1147552,2004.0,CL,...,F,In vitro oxidative metabolic stability measure...,in vitro oxidative metabolic stability measure...,chembl_hlm_intrinsic,8.0,8.000,8.00,0.954243,0.954243,0.954243
4,39099,CHEMBL303673,O=C(N[C@@H](Cc1ccccc1)[C@@H](O)CC(C(=O)NO)C1CC...,smiles_found,CHEMBL372,Homo sapiens,CHEMBL695026,CHEMBL1147552,2004.0,CL,...,F,In vitro oxidative metabolic stability measure...,in vitro oxidative metabolic stability measure...,chembl_hlm_intrinsic,6.1,6.100,6.10,0.851258,0.851258,0.851258
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11697,26316940,CHEMBL5712066,C=CC(=O)Nc1ccc(C(=O)NC2CCN(Cc3ccc(-c4nc5cc[nH]...,smiles_found,CHEMBL612558,ADMET,CHEMBL5712039,CHEMBL5705908,2019.0,CL,...,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic,12.0,12.336,10.08,1.113943,1.125026,1.044540
11698,26316941,CHEMBL2325741,NC1(C(=O)N[C@@H](CCO)c2ccc(Cl)cc2)CCN(c2nc[nH]...,smiles_found,CHEMBL612558,ADMET,CHEMBL5712039,CHEMBL5705908,2019.0,CL,...,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic,14.0,14.392,11.76,1.176091,1.187295,1.105851
11699,26316942,CHEMBL2177390,CC(C)NC[C@@H](C(=O)N1CCN(c2ncnc3c2[C@H](C)C[C@...,smiles_found,CHEMBL612558,ADMET,CHEMBL5712039,CHEMBL5705908,2019.0,CL,...,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic,12.0,12.336,10.08,1.113943,1.125026,1.044540
11700,26316943,CHEMBL1079175,NC1(c2ccc(-c3nc4ccn5c(=O)[nH]nc5c4cc3-c3ccccc3...,smiles_found,CHEMBL612558,ADMET,CHEMBL5712039,CHEMBL5705908,2019.0,CL,...,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic,1.0,1.028,0.84,0.301030,0.307068,0.264818
11701,26316944,CHEMBL4795065,C=CC(=O)Nc1ccc2[nH]c(=O)n(C3CCN(Cc4ccc(-c5nc6c...,smiles_found,CHEMBL612558,ADMET,CHEMBL5712039,CHEMBL5705908,2019.0,CL,...,A,Microsomal stability in human liver microsome ...,microsomal stability in human liver microsome ...,chembl_hlm_intrinsic,5.0,5.140,4.20,0.778151,0.788168,0.716003

Let's plot to see the results

In [22]:
df_inside_range["dataset"] = "chembl_dataset"
df_inside_range.to_csv("adjusted_datasets/chembl_hlm_adjusted_new.csv")

C:\Users\talag\AppData\Local\Temp\ipykernel_34132\1844735072.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_inside_range["dataset"] = "chembl_dataset"